trigger:
- main

variables:
- group: databricks-dev


pool:
  vmImage: ubuntu-latest

steps:

- script: |
    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  displayName: Install Databricks CLI

- script: |
    databricks bundle validate
  displayName: Validate Bundle
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

- script: |
    databricks bundle deploy -t dev
  displayName: Deploy Bundle
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
