trigger:
- main

variables:
- group: databricks-dev


pool:
  vmImage: ubuntu-latest

steps:

- script: |
    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  displayName: Install Databricks CLI


- script: |
    databricks workspace import \
      /Workspace/Users/sravani.geddada@inspirext.com/sample_notebook.py \
      --file sample_notebook.py \
      --format AUTO \
      --overwrite
  displayName: Upload Notebook
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
